name: shopm
description: A Flutter food delivery app for macaroni shop.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.10.3
  firebase_auth: ^4.17.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/meatballs.jpg
    - assets/cutlets.jpg
    - assets/burgers.jpg
    - assets/medallions.jpg
    - assets/caces.jpg

